# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0888b756d0d58358d339acfa5c096174cb7d0d6adfeb6c95e12495bd80f33c39637e6feda53c929720e2e5648c2fcfbb789d49a75ee67757af693b4ba244356a

test:
  secret_key_base: 5070b4721bf8efeaabee07d5b9998e52ae864bb59edce99969b4924cf021c8dcb6a0b190f4294e0c8551a6cec17446457e021eac177af9fffd1f36cb60c19dff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
